name: cooklens
description: "AR-powered recipe discovery platform"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
