name: cooklens
description: "AR-powered recipe discovery platform"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

  # DI
  get_it: ^8.0.2
  injectable: ^2.5.0

  # State management
  flutter_bloc: ^8.1.6

  # Code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # UI
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
